language: cpp

sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

compiler:
  - gcc
#  - clang

before_script:
  - pip2 install conan
  - mkdir build
  - cd build
  - conan install .. --build
  - cmake ..

script: make && make test

