language: c++
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-5.4 && export CXX="g++-5.4" CC="gcc-5.4"
      fi
    fi

before_script:
  - pip2 install conan
  - mkdir build
  - cd build
  - conan install .. --build
  - cmake ..

script: make && make test
